language: java

env:
  global:
    - SONATYPE_USERNAME=neothemachine
    - secure: "g60oYzXlSf19xevy4p8m40ibv8ld8kDf/SOJuaTaVD+mlNS8QiwLgEk4CETT\nmK6cEtxN7rSxnBYysBsSeKO5n8gagmivK/7LtiyzUDb1/elpyKXYYHFs2VFm\nW8iJCnLBbBM7bxuFB3JMNM68GKLSHgzNVXyJ9K1iVaQkKyUQm0c="
    
after_script:
  - python travis/addServer.py
  - mvn clean deploy -DskipTests=true --settings ~/.m2/mySettings.xml